In [3]:
import numpy as np
import pandas as pd
import os
WORKING_PATH = "C:/Users/carlo/Projects/Astronomy Research/"

In [ ]:
METADATA = ["Time", "Model"]
PHYSICAL_PARAMETERS = np.loadtxt(os.path.join(WORKING_PATH, "Main Scripts 11.9.24/utils/physical_parameters.txt"), dtype=str, delimiter=" ").tolist()
TOTAL_SPECIES = np.loadtxt(os.path.join(WORKING_PATH, "Main Scripts 11.9.24/utils/species.txt"), dtype=str, delimiter=" ").tolist()

['Density', 'Radfield', 'av', 'gasTemp']
['Density', 'Radfield', 'av', 'gasTemp']
['Density', 'Radfield', 'av', 'gasTemp']


In [9]:
x = np.array([1,2,3,4,5])

print(x/x)
print(10**x)
print(np.log10(10**x))

[1. 1. 1. 1. 1.]
[    10    100   1000  10000 100000]
[1. 2. 3. 4. 5.]


In [4]:
df = pd.read_hdf(os.path.join(WORKING_PATH, "Datasets/training.h5"), "autoencoder", start=0, stop=1000)
print(df.head())

     Time   Density  gasTemp        av          HSIO         H          NumH  \
5   0.001  562340.0      5.0  0.048391  1.000000e-20  0.937004  4.182880e-07   
6   0.010  562340.0      5.0  0.048391  1.000000e-20  0.937000  2.888030e-06   
7   0.100  562340.0      5.0  0.048391  1.000000e-20  0.936960  4.878410e-06   
8   1.000  562340.0      5.0  0.048391  1.000000e-20  0.936567  4.879020e-06   
9  10.000  562340.0      5.0  0.048391  1.000000e-20  0.932640  4.878860e-06   

          HPlus           AtH        H2  ...        NumHS2         AtHS2  \
5  1.000000e-20  1.902580e-08  0.031498  ...  1.000000e-20  1.000000e-20   
6  1.000000e-20  1.485090e-06  0.031498  ...  1.000000e-20  1.000000e-20   
7  1.000000e-20  3.885190e-05  0.031497  ...  1.000000e-20  1.000000e-20   
8  1.000000e-20  4.323320e-04  0.031489  ...  1.000000e-20  1.000000e-20   
9  1.000000e-20  4.358060e-03  0.031408  ...  1.000000e-20  1.000000e-20   

       H2S2Plus          H2S2       NumH2S2        AtH2S2     

In [30]:
df.reset_index().loc[20].sort_values(ascending=False)[6:]

BULK        9.696550e-01
AtH         9.388380e-01
HE          1.000000e-01
av          4.839100e-02
AtH2        3.030410e-02
                ...     
HNO         1.000000e-20
HNOPlus     1.000000e-20
SIH3        1.000000e-20
SIH3Plus    1.000000e-20
SIH4        1.000000e-20
Name: 20, Length: 335, dtype: float64

In [2]:
import pandas as pd

data = {'A': range(1, 11), 'B': range(11, 21)}
df = pd.DataFrame(data)

df['pair_group'] = df.index // 2

grouped = df.groupby('pair_group')

pair_means = grouped.mean()

for name, group in grouped:
    print(f"Pair {name}:\n", group, "\n")


Pair 0:
    A   B  pair_group
0  1  11           0
1  2  12           0 

Pair 1:
    A   B  pair_group
2  3  13           1
3  4  14           1 

Pair 2:
    A   B  pair_group
4  5  15           2
5  6  16           2 

Pair 3:
    A   B  pair_group
6  7  17           3
7  8  18           3 

Pair 4:
     A   B  pair_group
8   9  19           4
9  10  20           4 



In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = pd.read_hdf(os.path.join(WORKING_PATH, "Datasets/training.h5"), "emulator", start=0, stop=5)

df = np.log10(df)

global_min = df.min().min()  # minimum value across all columns
global_max = df.max().max()  # maximum value across all columns

#scaled_df = (df - global_min) / (global_max - global_min)


scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(
    np.array([global_min, global_max]).reshape(-1, 1)
)
print(scaler.data_min_)



scaled_df

[-20.]


Time  Density   gasTemp        av  HSIO         H      NumH  HPlus  \
91  0.932207      1.0  0.803843  0.725622   0.0  0.697473  0.569102    0.0   
92  0.933799      1.0  0.803843  0.725622   0.0  0.690280  0.568910    0.0   
93  0.935254      1.0  0.803843  0.725622   0.0  0.683377  0.568727    0.0   
94  0.936593      1.0  0.803843  0.725622   0.0  0.676863  0.568569    0.0   
95  0.937834      1.0  0.803843  0.725622   0.0  0.670857  0.568451    0.0   

         AtH        H2  ...  NumHS2  AtHS2  H2S2Plus  H2S2  NumH2S2  AtH2S2  \
91  0.775466  0.666549  ...     0.0    0.0       0.0   0.0      0.0     0.0   
92  0.775525  0.661117  ...     0.0    0.0       0.0   0.0      0.0     0.0   
93  0.775563  0.655661  ...     0.0    0.0       0.0   0.0      0.0     0.0   
94  0.775588  0.650211  ...     0.0    0.0       0.0   0.0      0.0     0.0   
95  0.775604  0.644802  ...     0.0    0.0       0.0   0.0      0.0     0.0   

        BULK   SURFACE  Radfield     Model  
91  0.775995  0.570772  0.824582  0.776699  
92  0.776059  0.570772  0.824582  0.776699  
93  0.776101  0.570772  0.824582  0.776699  
94  0.776128  0.570772  0.824582  0.776699  
95  0.776145  0.570772  0.824582  0.776699  

[5 rows x 340 columns]

In [14]:
components = [f"Component_{num}" for num in range(1, 12)]
components

['Component_1',
 'Component_2',
 'Component_3',
 'Component_4',
 'Component_5',
 'Component_6',
 'Component_7',
 'Component_8',
 'Component_9',
 'Component_10',
 'Component_11']

In [2]:
"""

INPUT: training.h5, validation.h5, abundances.scalers
OUTPUT: autoencoder.pth
"""

import os
import numpy as np
import pandas as pd
from datetime import datetime
from joblib import load
import torch
from torch import nn, optim, multiprocessing as mp
from torch.cuda.amp import GradScaler, autocast
from torch.distributed import init_process_group, destroy_process_group
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, DistributedSampler

### Configurations
WORKING_PATH = "C:/Users/carlo/Projects/Astronomy Research/"
HP = {
    "encoded_dimensions": 11,
    "learning_rate": 0.001,
    "weight_decay": 0,
    "batch_size": 2*4096,
    "shuffle": True,
    "gradient_clipping": 100,
    "early_stopping_tolerance": 7,
    "max_epochs": 999999,
    "hidden_layer": 5
}

METADATA = ["Time", "Model"] 
PHYSICAL_PARAMETERS = np.loadtxt(os.path.join(WORKING_PATH, "Main Scripts 11.9.24/utils/physical_parameters.txt"), dtype=str, delimiter=" ").tolist()
TOTAL_SPECIES = np.loadtxt(os.path.join(WORKING_PATH, "Main Scripts 11.9.24/utils/species.txt"), dtype=str, delimiter=" ").tolist()


### Data Processing Functions
def load_datasets(path):
    training_dataset_path = os.path.join(path, "Datasets/training.h5")
    validation_dataset_path = os.path.join(path, "Datasets/validation.h5")

    training_dataset = pd.read_hdf(training_dataset_path, "autoencoder", start=0, stop=1000).astype(np.float32)
    validation_dataset = pd.read_hdf(validation_dataset_path, "autoencoder", start=0, stop=1000).astype(np.float32)

    training_dataset = training_dataset[TOTAL_SPECIES]
    validation_dataset = validation_dataset[TOTAL_SPECIES]

    return training_dataset, validation_dataset


def autoencoder_preprocessing(abundances_features):
    ### Preprocesses the data for the autoencoder training. Returns a dataloader.
    print("Starting Encoder Preprocessing.")

    # Created using only the training data.
    scalers = load(os.path.join(WORKING_PATH, "Datasets/scalers.plk"))
    abundances_min, abundances_max = scalers["total_species"]

    # Log10 Scale Abundances and then MinMax scale.
    abundances_features = np.log10(abundances_features, dtype=np.float32)

    # Minmax scale all the abundances_features.
    abundances_features = (abundances_features - abundances_min) / (abundances_max - abundances_min)


    return abundances_features

In [32]:
WORKING_PATH = "C:/Users/carlo/Projects/Astronomy Research/"

training_dataset, validation_dataset = load_datasets(WORKING_PATH)

training = autoencoder_preprocessing(training_dataset)
training_dataset
row = training_dataset.loc[1]

# Sort the values in decreasing order, placing NaN first
sorted_row = row.sort_values(ascending=False, na_position='first')

sorted_row

Starting Encoder Preprocessing.


H         9.370000e-01
HE        1.000000e-01
H2        3.149790e-02
O         3.340000e-04
C         1.768810e-04
              ...     
COPlus    1.000000e-20
CO2       1.000000e-20
CO        1.000000e-20
CNPlus    1.000000e-20
HCS       1.000000e-20
Name: 1, Length: 334, dtype: float32

In [ ]:
import os
from joblib import load
WORKING_PATH = "C:/Users/carlo/Projects/Astronomy Research/"

scalers = load(os.path.join(WORKING_PATH, "Datasets/scalers.plk"))

scalers["encoded_components"] = (
    0,
    1
)

print(scalers)

{'Density': MinMaxScaler(), 'Radfield': MinMaxScaler(), 'av': MinMaxScaler(), 'gasTemp': MinMaxScaler(), 'total_species': (-20.0, 0.0), 'encoded_components': (0, 1)}


In [ ]:
WORKING_PATH = "C:/Users/carlo/Projects/Astronomy Research/"
training_dataset_path = os.path.join(WORKING_PATH, "Datasets/training.h5")
training_dataset = pd.read_hdf(training_dataset_path, "autoencoder", start=0).astype(np.float32)

z = training_dataset.mean()

In [2]:
import pandas as pd


data = {'A': range(1, 11), 'B': range(11, 21)}
df = pd.DataFrame(data)

print(df)
print(df.sum(axis=1).mean())


    A   B
0   1  11
1   2  12
2   3  13
3   4  14
4   5  15
5   6  16
6   7  17
7   8  18
8   9  19
9  10  20
0    12
1    14
2    16
3    18
4    20
5    22
6    24
7    26
8    28
9    30
dtype: int64
